# action.yaml

name: TrustCerts Custom Blockchain
description: 'Start a blockchain'
inputs:
  did_id:
    description: the id of the client
    required: true
    default: did:trust:tc:dev:id:XLzBJ69tqEgq7oqqCLiEnT
  network_size:
    description: choose the network size either small or normal
    required: true
    default: "small"
runs:
  using: composite

  steps:
    - run: |
        git submodule init
        git submodule update
      shell: bash
    - run: |
        export DID_ID=${{inputs.did_id}}
        export NETWORK_SIZE=${{inputs.network_size}}
        export GITHUB_PATH=${{github.action_path}}
        export NODE_PATH=${{github.action_path}}/trustchain-config/nodes
        chmod 777 ${{ github.action_path }}/setup.sh
        ${{ github.action_path }}/setup.sh
      shell: bash
