# action.yaml

name: TrustCerts Custom Blockchain
description: 'Start a blockchain'
inputs:
  did_id:
    description: the id of the client
    required: false
    default: did:trust:tc:test:id:XLzBJ69tqEgq7oqqCLiEnT
  network_size:
    description: choose the network size either small or normal
    required: false
    default: "small"
  client_name:
    description: name of the client
    required: false
    default: "client"
  client_secret:
    description: secret of the Client
    required: false
    default: "client"
  log_format:
    description: log format of docker containers
    required: false
    default: "log"
runs:
  using: 'node16'
  main: 'index.js'
  post: 'cleanup.js'

