# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: NAIRE
    cancelTimeoutInMinutes: 
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: NAIRE 
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
